services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

  bot:
    build: .
    env_file:
      - .env
    command: uv run python -m bot.handlers
    depends_on:
      - api
    restart: always

volumes:
  pgdata:
